# Generated by Django 3.1.3 on 2020-12-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eprojapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=None, null=True, upload_to='pics'),
        ),
    ]
