# Generated by Django 3.1.3 on 2020-12-11 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eprojapp', '0002_car_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_car',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eprojapp.car'),
            preserve_default=False,
        ),
    ]
